In [ ]:
import pandas as pd
import numpy as np
import re

# === Load data ===
shanghai = pd.read_csv(
    "shanghai_XU.csv",
    header=0,
    # usecols=[1, 3],
    dtype={"word": "string", 
           "sandhi_tone": "string",
           "syllable":"double"},
    )

shanghai = shanghai.dropna()

shanghai = shanghai.sample(frac=0.2, random_state=42).reset_index(drop=True)


# === Tone mapping ===
# print(f"Tonal inventory: {shanghai['Tone'].unique()}")

tone_map = {
    "4": "H",
    "5": "H",
    "3": "M",
    "1": "L",
    "2": "L",
    ".":"#"
}

def map_tone_sequence(seq):
    """Convert digit tone labels to letter labels."""
    if pd.isna(seq):
        return None
    return "".join(tone_map.get(ch, "") for ch in str(seq))

# shanghai["tone_letter"] = shanghai["Tone"].apply(map_tone_sequence)

# print(f"all characters: {''.join(sorted(set(''.join(shanghai['Form'].dropna().unique()))))}")

# === Feature extraction === # this could be provided by the users
feature_system = {
    
    "voc": {"a", "i", "u", "o", "e", "y", "ø", "ɑ", "ɔ", "ə", "ɤ", "ɪ", "ɿ", "A", "E", "ã", "ĩ", "ũ", "õ", "ẽ"},
    "son": {"l", "m", "n", "ɲ", "ŋ", "ȵ"},
    "cons": {"b", "d", "f", "h", "k", "l", "m", "n", "p", "s", "t", "v", "z", "ɲ", "ȵ", "ɕ", "ŋ", "ɡ", "ɦ", "ʑ", "ʔ", "ʥ", "ʦ", "ʨ"},
    "cg": {"ʔ", "ɦ","?"},
    "+voi": {"b", "d", "ɡ", "z", "v", "l", "j", "ɦ", "ʥ","ʑ"},
    "-voi": {"f", "h", "k", "p", "s", "t", "ʦ", "ʨ", "ʔ"},
    "#": {"#", "."},  # word boundary
}


# === Diacritic stripping ===
strip_diacritics = {
    "ʰ": "",   # superscript h
    "̃": "",   # combining tilde
    "̍": "",   # combining vertical line above
}

def replace_diacritics(s):
    s = str(s)
    for old, new in strip_diacritics.items():
        s = s.replace(old, new)
    return s

shanghai["word"] = shanghai["word"].apply(replace_diacritics)


def get_feature(form):
    """Map characters in Form to a simplified structural code."""
    word_feat = []
    syl_feat = []
    syllables = str(form).split('.')
    for i in syllables:
        for ch in str(i):
            seg_feature = {key for key, values in feature_system.items() if ch in values}
            syl_feat.append(seg_feature)
        word_feat.append(syl_feat)    
    return word_feat

shanghai["feature"] = shanghai["word"].apply(get_feature)

shanghai["SR"] = shanghai["sandhi_tone"].apply(map_tone_sequence)

# print(f"all characters: {''.join(sorted(set(''.join(shanghai['Form'].dropna().unique()))))}")

In [ ]:
print("The corpus shows some superheavy structures inconsistent with literature such as:")

# flatten the (potentially ragged) nested list of features safely

shanghai['flatten_features'] = shanghai['feature'].apply(lambda feats: [feat for seg in feats for feat in seg])

shanghai = shanghai[~(shanghai["flatten_features"].apply(lambda x: x.count("voc") >= 3))]
# Remove forms ending with glides or allophonic il syllables

#add onset register
def find_onset_register(feature_list,word):
    """Determine the onset register of a syllable."""
    for i, syl in enumerate(word.split('.')):
        first_char = syl[0]
        
    
        if first_char in feature_system["upper"]:
            feature_list[i].append("U") 
        elif first_char in feature_system["lower"]:
            feature_list[i].append("L")
        else:
            feature_list[i].append("NA")
    return feature_list
shanghai["feature"] = shanghai['feature'].apply(find_onset_register(shanghai["word"]))
shanghai

The corpus shows some superheavy structures inconsistent with literature such as:

,word,mandarin,gloss,cittation_tone,sandhi_tone,syllable,feature,SR,flatten_features,Register,features_replaced
0,ɦiA.soʔ,爷叔,"uncle (colloquial, respectful)",T3.T4,22.44,2.0,"[[{+voi, cg, cons}, {voc}, {voc}, {-voi, cons}...",LL#HH,"[{+voi, cg, cons}, {voc}, {voc}, {-voi, cons},...",U,"[[{+voi, cg, cons}, {voc}, {voc}, {-voi, cons}..."
1,pE.vən,辈分,seniority; generation (in family),T2.T3,55.21,2.0,"[[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {s...",HH#LL,"[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {so...",L,"[[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {s..."
2,ɦəʔ.poʔ,合扑,to fit together; to match,T5.T4,11.23,2.0,"[[{+voi, cg, cons}, {voc}, {-voi, cg, cons}, {...",LL#LM,"[{+voi, cg, cons}, {voc}, {-voi, cg, cons}, {-...",U,"[[{+voi, cg, cons}, {voc}, {-voi, cg, cons}, {..."
3,u.zəʔ,乌贼,squid,T1.T5,55.21,2.0,"[[{voc}, {+voi, cons}, {voc}, {-voi, cg, cons}...",HH#LL,"[{voc}, {+voi, cons}, {voc}, {-voi, cg, cons},...",L,"[[{voc}, {+voi, cons}, {voc}, {-voi, cg, cons}..."
4,zA?,石,stone,T5,12,1.0,"[[{+voi, cons}, {voc}, {cg}]]",LL,"[{+voi, cons}, {voc}, {cg}]",U,"[[{+voi, cons}, {voc}, {cg}]]"
5,zəʔ,食,food,T5,12,1.0,"[[{+voi, cons}, {voc}, {-voi, cg, cons}]]",LL,"[{+voi, cons}, {voc}, {-voi, cg, cons}]",U,"[[{+voi, cons}, {voc}, {-voi, cg, cons}]]"
6,ʑin.zAʔ,寻着,to find,T3.T5,22.44,2.0,"[[{+voi, cons}, {voc}, {son, cons}, {+voi, con...",LL#HH,"[{+voi, cons}, {voc}, {son, cons}, {+voi, cons...",U,"[[{+voi, cons}, {voc}, {son, cons}, {+voi, con..."
7,ɕiɔ.təʔ,晓得,to know; to understand,T2.T4,33.44,2.0,"[[{cons}, {voc}, {voc}, {-voi, cons}, {voc}, {...",MM#HH,"[{cons}, {voc}, {voc}, {-voi, cons}, {voc}, {-...",L,"[[{cons}, {voc}, {voc}, {-voi, cons}, {voc}, {..."
8,sã.kã,霜降,frost descent (solar term),T1.T2,55.21,2.0,"[[{-voi, cons}, {voc}, {-voi, cons}, {voc}], [...",HH#LL,"[{-voi, cons}, {voc}, {-voi, cons}, {voc}, {-v...",L,"[[{-voi, cons}, {voc}, {-voi, cons}, {voc}], [..."
9,tɔ,刀,knife,T1,53,1.0,"[[{-voi, cons}, {voc}]]",HM,"[{-voi, cons}, {voc}]",L,"[[{-voi, cons}, {voc}]]"
10,tɕin.tsɿ,景致,scenery; view,T2.T2,33.44,2.0,"[[{-voi, cons}, {cons}, {voc}, {son, cons}, {-...",MM#HH,"[{-voi, cons}, {cons}, {voc}, {son, cons}, {-v...",L,"[[{-voi, cons}, {cons}, {voc}, {son, cons}, {-..."
11,to?.din,笃定,determined,T4.T3,33.44,2.0,"[[{-voi, cons}, {voc}, {cg}, {+voi, cons}, {vo...",MM#HH,"[{-voi, cons}, {voc}, {cg}, {+voi, cons}, {voc...",L,"[[{-voi, cons}, {voc}, {cg}, {+voi, cons}, {vo..."
12,dɔ,导,guide,T3,23,1.0,"[[{+voi, cons}, {voc}]]",LM,"[{+voi, cons}, {voc}]",U,"[[{+voi, cons}, {voc}]]"
13,sy.ɕin,手心,palm (of the hand),T2.T1,33.44,2.0,"[[{-voi, cons}, {voc}, {cons}, {voc}, {son, co...",MM#HH,"[{-voi, cons}, {voc}, {cons}, {voc}, {son, con...",L,"[[{-voi, cons}, {voc}, {cons}, {voc}, {son, co..."
14,sɤ.zo?,手镯,bracelet,T2.T5,33.44,2.0,"[[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {c...",MM#HH,"[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {cg...",L,"[[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {c..."
15,pa,爸,father,T1,53,1.0,"[[{-voi, cons}, {voc}]]",HM,"[{-voi, cons}, {voc}]",L,"[[{-voi, cons}, {voc}]]"
16,tɕiã,酱,sauce,T2,34,1.0,"[[{-voi, cons}, {cons}, {voc}, {voc}]]",MH,"[{-voi, cons}, {cons}, {voc}, {voc}]",L,"[[{-voi, cons}, {cons}, {voc}, {voc}]]"
17,hø.mi,虾米,dried shrimp,T1.T3,55.21,2.0,"[[{-voi, cons}, {voc}, {son, cons}, {voc}], [{...",HH#LL,"[{-voi, cons}, {voc}, {son, cons}, {voc}, {-vo...",L,"[[{-voi, cons}, {voc}, {son, cons}, {voc}], [{..."
18,ɦyɪʔ.pø,月半,mid-month; half month,T5.T2,11.23,2.0,"[[{+voi, cg, cons}, {voc}, {voc}, {-voi, cg, c...",LL#LM,"[{+voi, cg, cons}, {voc}, {voc}, {-voi, cg, co...",U,"[[{+voi, cg, cons}, {voc}, {voc}, {-voi, cg, c..."
19,səʔ.dɤ,塞头,plug; stopper,T4.T3,33.44,2.0,"[[{-voi, cons}, {voc}, {-voi, cg, cons}, {+voi...",MM#HH,"[{-voi, cons}, {voc}, {-voi, cg, cons}, {+voi,...",L,"[[{-voi, cons}, {voc}, {-voi, cg, cons}, {+voi..."

In [132]:
def replace_voc_with_tones(row):
    features = row["feature"]
    tones = row["SR"]

    # Split tone string by '#' to get tone sequences
    tone_segments = tones.split('#')

    new_features = []
    tone_index = 0

    for f in features:
        if 'voc' in f:
            # Replace 'voc' cell with corresponding tone segment
            if tone_index < len(tone_segments):
                new_features.append([tone_segments[tone_index]])
                tone_index += 1
            else:
                # In case of mismatch, just keep 'voc' to avoid crash
                new_features.append(['voc'])
        else:
            new_features.append(f)

    return new_features


# Apply to each row
shanghai["features_replaced"] = shanghai.apply(replace_voc_with_tones, axis=1)

shanghai

,word,mandarin,gloss,cittation_tone,sandhi_tone,syllable,feature,SR,flatten_features,Register,features_replaced
0,ɦiA.soʔ,爷叔,"uncle (colloquial, respectful)",T3.T4,22.44,2.0,"[[{+voi, cg, cons}, {voc}, {voc}, {-voi, cons}...",LL#HH,"[{+voi, cg, cons}, {voc}, {voc}, {-voi, cons},...",U,"[[{+voi, cg, cons}, {voc}, {voc}, {-voi, cons}..."
1,pE.vən,辈分,seniority; generation (in family),T2.T3,55.21,2.0,"[[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {s...",HH#LL,"[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {so...",L,"[[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {s..."
2,ɦəʔ.poʔ,合扑,to fit together; to match,T5.T4,11.23,2.0,"[[{+voi, cg, cons}, {voc}, {-voi, cg, cons}, {...",LL#LM,"[{+voi, cg, cons}, {voc}, {-voi, cg, cons}, {-...",U,"[[{+voi, cg, cons}, {voc}, {-voi, cg, cons}, {..."
3,u.zəʔ,乌贼,squid,T1.T5,55.21,2.0,"[[{voc}, {+voi, cons}, {voc}, {-voi, cg, cons}...",HH#LL,"[{voc}, {+voi, cons}, {voc}, {-voi, cg, cons},...",L,"[[{voc}, {+voi, cons}, {voc}, {-voi, cg, cons}..."
4,zA?,石,stone,T5,12,1.0,"[[{+voi, cons}, {voc}, {cg}]]",LL,"[{+voi, cons}, {voc}, {cg}]",U,"[[{+voi, cons}, {voc}, {cg}]]"
5,zəʔ,食,food,T5,12,1.0,"[[{+voi, cons}, {voc}, {-voi, cg, cons}]]",LL,"[{+voi, cons}, {voc}, {-voi, cg, cons}]",U,"[[{+voi, cons}, {voc}, {-voi, cg, cons}]]"
6,ʑin.zAʔ,寻着,to find,T3.T5,22.44,2.0,"[[{+voi, cons}, {voc}, {son, cons}, {+voi, con...",LL#HH,"[{+voi, cons}, {voc}, {son, cons}, {+voi, cons...",U,"[[{+voi, cons}, {voc}, {son, cons}, {+voi, con..."
7,ɕiɔ.təʔ,晓得,to know; to understand,T2.T4,33.44,2.0,"[[{cons}, {voc}, {voc}, {-voi, cons}, {voc}, {...",MM#HH,"[{cons}, {voc}, {voc}, {-voi, cons}, {voc}, {-...",L,"[[{cons}, {voc}, {voc}, {-voi, cons}, {voc}, {..."
8,sã.kã,霜降,frost descent (solar term),T1.T2,55.21,2.0,"[[{-voi, cons}, {voc}, {-voi, cons}, {voc}], [...",HH#LL,"[{-voi, cons}, {voc}, {-voi, cons}, {voc}, {-v...",L,"[[{-voi, cons}, {voc}, {-voi, cons}, {voc}], [..."
9,tɔ,刀,knife,T1,53,1.0,"[[{-voi, cons}, {voc}]]",HM,"[{-voi, cons}, {voc}]",L,"[[{-voi, cons}, {voc}]]"
10,tɕin.tsɿ,景致,scenery; view,T2.T2,33.44,2.0,"[[{-voi, cons}, {cons}, {voc}, {son, cons}, {-...",MM#HH,"[{-voi, cons}, {cons}, {voc}, {son, cons}, {-v...",L,"[[{-voi, cons}, {cons}, {voc}, {son, cons}, {-..."
11,to?.din,笃定,determined,T4.T3,33.44,2.0,"[[{-voi, cons}, {voc}, {cg}, {+voi, cons}, {vo...",MM#HH,"[{-voi, cons}, {voc}, {cg}, {+voi, cons}, {voc...",L,"[[{-voi, cons}, {voc}, {cg}, {+voi, cons}, {vo..."
12,dɔ,导,guide,T3,23,1.0,"[[{+voi, cons}, {voc}]]",LM,"[{+voi, cons}, {voc}]",U,"[[{+voi, cons}, {voc}]]"
13,sy.ɕin,手心,palm (of the hand),T2.T1,33.44,2.0,"[[{-voi, cons}, {voc}, {cons}, {voc}, {son, co...",MM#HH,"[{-voi, cons}, {voc}, {cons}, {voc}, {son, con...",L,"[[{-voi, cons}, {voc}, {cons}, {voc}, {son, co..."
14,sɤ.zo?,手镯,bracelet,T2.T5,33.44,2.0,"[[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {c...",MM#HH,"[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {cg...",L,"[[{-voi, cons}, {voc}, {+voi, cons}, {voc}, {c..."
15,pa,爸,father,T1,53,1.0,"[[{-voi, cons}, {voc}]]",HM,"[{-voi, cons}, {voc}]",L,"[[{-voi, cons}, {voc}]]"
16,tɕiã,酱,sauce,T2,34,1.0,"[[{-voi, cons}, {cons}, {voc}, {voc}]]",MH,"[{-voi, cons}, {cons}, {voc}, {voc}]",L,"[[{-voi, cons}, {cons}, {voc}, {voc}]]"
17,hø.mi,虾米,dried shrimp,T1.T3,55.21,2.0,"[[{-voi, cons}, {voc}, {son, cons}, {voc}], [{...",HH#LL,"[{-voi, cons}, {voc}, {son, cons}, {voc}, {-vo...",L,"[[{-voi, cons}, {voc}, {son, cons}, {voc}], [{..."
18,ɦyɪʔ.pø,月半,mid-month; half month,T5.T2,11.23,2.0,"[[{+voi, cg, cons}, {voc}, {voc}, {-voi, cg, c...",LL#LM,"[{+voi, cg, cons}, {voc}, {voc}, {-voi, cg, co...",U,"[[{+voi, cg, cons}, {voc}, {voc}, {-voi, cg, c..."
19,səʔ.dɤ,塞头,plug; stopper,T4.T3,33.44,2.0,"[[{-voi, cons}, {voc}, {-voi, cg, cons}, {+voi...",MM#HH,"[{-voi, cons}, {voc}, {-voi, cg, cons}, {+voi,...",L,"[[{-voi, cons}, {voc}, {-voi, cg, cons}, {+voi..."

In [43]:
# === Embed tone in vowel ===
def embed_tone_in_vowel(tone, syl):
    simplied_form = list(syl)  # make it mutable
    v_positions = [i for i, c in enumerate(simplied_form) if c == "V"]

    if len(tone) == 1 and len(v_positions) == 1:
        if tone == "H":
            simplied_form = syl.replace("V", "á")
        elif tone == "L":
            simplied_form = syl.replace("V", "à")
        elif tone == "M":    
            simplied_form = syl.replace("V", "a")   
            
    elif len(tone) == 2 and len(v_positions) == 1:
        if tone == "MH":
             simplied_form = syl.replace("V", "â")
        elif tone == "HM":
             simplied_form = syl.replace("V", "ǎ")
        elif tone == "LM":    
             simplied_form = syl.replace("V", "ā")   
    
    elif len(tone) == 2 and len(v_positions) == 2:  # match
        if tone == "MH":
            simplied_form = syl.replace("VV", "â")
        elif tone == "HM":
            simplied_form = syl.replace("VV", "ǎ")
        elif tone == "LM":    
            simplied_form = syl.replace("VV", "ā")
            
    elif len(v_positions) == 0:
        if tone == "MH":
            simplied_form = syl.replace("N", "ń")
        elif tone == "HM":
            simplied_form = syl.replace("N", "ň")
        elif tone == "LM":    
            simplied_form = syl.replace("N", "ņ")
    simplied_form += ''
        
    return " ".join(simplied_form)
shanghai

,word,mandarin,gloss,cittation_tone,sandhi_tone,syllable,feature,SR,flatten_features
0,tɔ,刀,knife,T1,53,1.0,"[[cons, -voi], [voc]]",HM,"[cons, -voi, voc]"
1,toŋ,东,east,T1,53,1.0,"[[cons, -voi], [voc], [son, cons]]",HM,"[cons, -voi, voc, son, cons]"
2,tsɿ,知,know,T1,53,1.0,"[[cons, -voi], [cons, -voi], [voc]]",HM,"[cons, -voi, cons, -voi, voc]"
3,tɕiã,浆,thick liquid,T1,53,1.0,"[[cons, -voi], [cons], [voc], [voc]]",HM,"[cons, -voi, cons, voc, voc]"
4,pa,爸,father,T1,53,1.0,"[[cons, -voi], [voc]]",HM,"[cons, -voi, voc]"
...,...,...,...,...,...,...,...,...,...
98,dəʔ.di,特地,specially; deliberately,T5.T3,11.23,2.0,"[[cons, +voi], [voc], [cons, cg, -voi], [#], [...",LL#LM,"[cons, +voi, voc, cons, cg, -voi, #, cons, +vo..."
99,loʔ.toʔ,落拓,unrestrained; carefree,T5.T4,11.23,2.0,"[[son, cons, +voi], [voc], [cons, cg, -voi], [...",LL#LM,"[son, cons, +voi, voc, cons, cg, -voi, #, cons..."
100,ɦəʔ.poʔ,合扑,to fit together; to match,T5.T4,11.23,2.0,"[[cons, cg, +voi], [voc], [cons, cg, -voi], [#...",LL#LM,"[cons, cg, +voi, voc, cons, cg, -voi, #, cons,..."
101,zAʔ.zəʔ,着实,indeed; truly,T5.T5,11.23,2.0,"[[cons, +voi], [voc], [cons, cg, -voi], [#], [...",LL#LM,"[cons, +voi, voc, cons, cg, -voi, #, cons, +vo..."
103,məʔ.loʔ,墨绿,jade green,T5.T5,11.23,2.0,"[[son, cons], [voc], [cons, cg, -voi], [#], [s...",LL#LM,"[son, cons, voc, cons, cg, -voi, #, son, cons,..."

In [95]:

shanghai["with_tone"] = shanghai.apply(
    lambda row: embed_tone_in_vowel(row["tone_letter"], row["simple"]), axis=1
)


shanghai_tone = pd.Series(shanghai['with_tone'].unique())
shanghai_tone.to_csv("~/Documents/BUFIA/data/shanghai_data.txt", index=False, header=False)

shanghai_tone

0       á g
1     T á g
2       â N
3         â
4       T â
5     T â N
6       N â
7     N â N
8       G â
9         ň
10        ǎ
11      ǎ N
12      T ǎ
13    T ǎ N
14      N ǎ
15    N ǎ N
16      G ǎ
17    D à g
18    N à g
19    G à g
20      D ā
21    D ā N
22      N ā
23    N ā N
24      ā N
25        ā
26    G ā N
27      G ā
28      G ņ
dtype: object

In [98]:

# symbols (from your inventory)
all_symbol = sorted(
    set(''.join(shanghai['with_tone'].dropna().unique()).replace(" ", "")) | {"ń"}
)

print(f"Symbols: {all_symbol}")

features = [
    "nas",      # nasal consonant
    "cons",      # nasal consonant
    "son",      # sonorant consonant
    "voi",        # voiced consonant
    "cg",         # consonantal glottalization
    "H",      # upper register tone
    "L",      # upper register tone
    "short"
]

# create DataFrame with "0" everywhere
df = pd.DataFrame("0", index=features, columns=all_symbol)

# example: fill in a few cells manually
# make every symbol "-" first

df.loc["cons"] = "-"
df.loc["cons", ['T','D','G','N','g','ń', 'ņ', 'ň']] = "+"


df.loc["son"] = "+"
df.loc["son", ['T','D','G','g']] = "-"

df.loc["nas"] = "-"
df.loc["nas", ['N','ń','ņ','ň']] = "+"

df.loc["voi"] = "+"
df.loc["voi", ['T','g']] = "-"

df.loc["cg"] = "-"
df.loc["cg", ['G','g']] = "+"


df.loc["H"] = "0"
df.loc["H", ['á','ǎ','ň']] = "+"
df.loc["H", ['à','â','ā','ń','ņ']] = "-"

df.loc["L"] = "0"
df.loc["L", ['à','ā','ņ']] = "+"
df.loc["L", ['á','ǎ','â','ń','ň']] = "-"

df.loc["short"] = "0"
df.loc["short", ['á','à']] = "+"
df.loc["short", ['â','ń','ņ','ň','ǎ','ā']] = "-"


df.loc["fall"] = "0"
df.loc["fall", ['ň','ǎ']] = "+"
df.loc["fall", ['â','ń','á','à','ņ','ā']] = "-"


print(df)

df.to_csv("~/Documents/BUFIA/data/shanghai_features.csv")
# shanghai

Symbols: ['D', 'G', 'N', 'T', 'g', 'à', 'á', 'â', 'ā', 'ń', 'ņ', 'ň', 'ǎ']
       D  G  N  T  g  à  á  â  ā  ń  ņ  ň  ǎ
nas    -  -  +  -  -  -  -  -  -  +  +  +  -
cons   +  +  +  +  +  -  -  -  -  +  +  +  -
son    -  -  +  -  -  +  +  +  +  +  +  +  +
voi    +  +  +  -  -  +  +  +  +  +  +  +  +
cg     -  +  -  -  +  -  -  -  -  -  -  -  -
H      0  0  0  0  0  -  +  -  -  -  -  +  +
L      0  0  0  0  0  +  -  -  +  -  +  -  -
short  0  0  0  0  0  +  +  -  -  -  -  -  -
fall   0  0  0  0  0  -  -  -  -  -  -  +  +

In [87]:
# search for certain type
filtered = shanghai[
	(shanghai['with_tone'].str.startswith('D'))&
 (shanghai['tone_letter'].str.startswith('H'))][['Form', 'tone_letter', 'Tone', 'with_tone']]
print(f"After filtering: {filtered.values.tolist()}")

After filtering: []

In [1]:
random_sample = shanghai.sample(n=10, random_state=1)[['Form', 'tone_letter', 'Tone', 'with_tone']]

NameError: name 'shanghai' is not defined